rule all:
    input:
        "summary_python.csv"

rule summarize_python:
    input:
        csv="data/example.csv"
    output:
        "summary_python.csv"
    conda:
        "environment.yml"
    shell:
        "python summarize.py"
