site_name: GCE Sustainable Code & Data Handbook
site_url: https://globalchangeecology.github.io/gce-sustainable-code-and-data-handbook/
repo_url: https://github.com/GlobalChangeEcology/gce-sustainable-code-and-data-handbook
repo_name: GlobalChangeEcology/gce-sustainable-code-and-data-handbook
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  logo: images/logo_only.jpg
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js

nav:
  - Start Here: START_HERE.md
  - Quick Starts:
      - Python: QUICK_START_PYTHON.md
      - R: QUICK_START_R.md
  - Glossary: GLOSSARY.md
  - FAQ: FAQ.md
  - Tools: TOOLS.md
  - Releases: RELEASES.md
  - Decision Guide: DECISION_GUIDE.md
  - Diagrams: DIAGRAMS.md
  - Handbook:
      - Policy & Principles: manual/01_POLICY_AND_PRINCIPLES.md
      - Project Setup: manual/02_PROJECT_SETUP.md
      - Metadata & Documentation: manual/03_METADATA_AND_DOCUMENTATION.md
      - Data Lifecycle: manual/04_DATA_LIFECYCLE.md
      - File & Version Control: manual/05_FILE_AND_VERSION_CONTROL.md
      - Data Quality: manual/06_DATA_QUALITY.md
      - Sensitive Data: manual/07_SENSITIVE_DATA.md
      - Tools & Platforms: manual/08_TOOLS_AND_PLATFORMS.md
      - Publishing & Reuse: manual/09_PUBLISHING_AND_REUSE.md
      - Checklists & Templates: manual/10_CHECKLISTS_AND_TEMPLATES.md
      - Software Practices: manual/11_SOFTWARE_PRACTICES.md
  - Implementation Guide: IMPLEMENTATION_GUIDE.md
  - Examples:
      - Minimal Project: examples/minimal-project/README.md
  - Tools (How-to):
      - Dataset Docs Generator: tools/generator.md
