site_name: GCE Sustainable Code & Data Handbook
site_url: https://globalchangeecology.github.io/gce-sustainable-code-and-data-handbook/
repo_url: https://github.com/GlobalChangeEcology/gce-sustainable-code-and-data-handbook
repo_name: GlobalChangeEcology/gce-sustainable-code-and-data-handbook
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  logo: images/logo_only.jpg
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
extra_css:
  - css/chips.css

nav:
  - Start:
    - Start Here: START_HERE.md
    - Pathways by Role: roles/INDEX.md
    - Decision Guide: DECISION_GUIDE.md
    - Onboarding (60 min): start/ONBOARDING_60_MIN.md
  - Course:
    - Overview: guide/INDEX.md
    - Phase Checklists: guide/CHECKLISTS.md
    - 1) Plan & Setup: guide/PHASE_01_PLAN_SETUP.md
    - 2) Repo & Structure: guide/PHASE_02_REPO_STRUCTURE.md
    - 3) Capture Metadata: guide/PHASE_03_METADATA.md
    - 4) Data & Versions: guide/PHASE_04_DATA_VERSIONING.md
    - 5) Environments: guide/PHASE_05_ENVIRONMENTS.md
    - 6) Validate & Clean: guide/PHASE_06_QUALITY.md
    - 7) Analyze & Document: guide/PHASE_07_ANALYZE.md
    - 8) Automate Pipelines: guide/PHASE_08_PIPELINES.md
    - 9) Publish & Cite: guide/PHASE_09_PUBLISH.md
    - Publish & Make Findable: guide/PUBLISH_AND_DISCOVER.md
    - 10) Archive & Hand-off: guide/PHASE_10_ARCHIVE.md
  - Exercises:
    - Quick Starts:
      - Python: QUICK_START_PYTHON.md
      - R: QUICK_START_R.md
    - Tutorials:
      - Git (Slidev): tutorials/GIT_TUTORIAL.md
      - Git — Embedded Slides: tutorials/GIT_TUTORIAL_EMBED.md
      - Git — Printable Summary: tutorials/GIT_TUTORIAL_SUMMARY.md
      - Conda Environments: tutorials/CONDA_TUTORIAL.md
      - Snakemake Basics: tutorials/SNAKEMAKE_TUTORIAL.md
      - GitHub Actions Basics: tutorials/GHA_TUTORIAL.md
    - Biology:
      - DwC → GBIF via IPT: exercises/BIO_DWC_GBIF.md
    - Examples:
      - Minimal Project: examples/minimal-project/README.md
  - Recipes:
    - Overview: recipes/INDEX.md
    - Deposit & Validation: data-management/DEPOSIT_AND_VALIDATION_RECIPES.md
    - Tools:
      - Dataset Docs Generator: tools/generator.md
  - Domains:
    - Overview: domain/INDEX.md
    - Biosciences: domain/BIOSCIENCES.md
    - Geospatial: domain/GEOSPATIAL.md
  - Reference:
    - Basics:
      - Reproducibility 101: basics/INDEX.md
      - FAIR in Practice: basics/FAIR.md
      - Ethics & Consent: basics/ETHICS_AND_CONSENT.md
    - Data Management:
      - Overview: data-management/INDEX.md
      - Data Versioning: data-management/DATA_VERSIONING.md
      - Archiving & Fixity: data-management/ARCHIVING_AND_FIXITY.md
      - Choosing a Repository: data-management/REPOSITORIES_MATRIX.md
    - Findability & Discovery (Beginner): reference/FINDABILITY_DISCOVERY.md
    - Advanced:
      - Dataset JSON-LD: discovery/DATASET_JSONLD.md
      - Advanced Git: git/ADVANCED.md
      - Git Recipes: git/RECIPES.md
    - Glossary: GLOSSARY.md
    - FAQ: FAQ.md
    - Tools Overview: TOOLS.md
    - Handbook:
      - Policy & Principles: manual/01_POLICY_AND_PRINCIPLES.md
      - Project Setup: manual/02_PROJECT_SETUP.md
      - Metadata & Documentation: manual/03_METADATA_AND_DOCUMENTATION.md
      - Data Lifecycle: manual/04_DATA_LIFECYCLE.md
      - File & Version Control: manual/05_FILE_AND_VERSION_CONTROL.md
      - Data Quality: manual/06_DATA_QUALITY.md
      - Sensitive Data: manual/07_SENSITIVE_DATA.md
      - Tools & Platforms: manual/08_TOOLS_AND_PLATFORMS.md
      - Publishing & Reuse: manual/09_PUBLISHING_AND_REUSE.md
      - Checklists & Templates: manual/10_CHECKLISTS_AND_TEMPLATES.md
      - Software Practices: manual/11_SOFTWARE_PRACTICES.md
    - Implementation Guide: IMPLEMENTATION_GUIDE.md
  - About:
    - Releases: RELEASES.md
    - Inspirations: INSPIRATION.md
    - Diagrams: DIAGRAMS.md
