site_name: GCE Sustainable Code & Data Handbook
site_url: https://globalchangeecology.github.io/gce-sustainable-code-and-data-handbook/
repo_url: https://github.com/GlobalChangeEcology/gce-sustainable-code-and-data-handbook
repo_name: GlobalChangeEcology/gce-sustainable-code-and-data-handbook
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  logo: images/logo_only.jpg
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js

nav:
  - Start Here: START_HERE.md
  - Basics:
    - Reproducibility 101: basics/INDEX.md
    - FAIR in Practice: basics/FAIR.md
  - Quick Starts:
      - Python: QUICK_START_PYTHON.md
      - R: QUICK_START_R.md
  - Glossary: GLOSSARY.md
  - FAQ: FAQ.md
  - Tools: TOOLS.md
  - Data Management:
    - Data Versioning: data-management/DATA_VERSIONING.md
    - Archiving & Fixity: data-management/ARCHIVING_AND_FIXITY.md
    - Choosing a Repository: data-management/REPOSITORIES_MATRIX.md
  - Domain Guides:
    - Geospatial: domain/GEOSPATIAL.md
  - Discovery:
    - Dataset JSON-LD: discovery/DATASET_JSONLD.md
  - Git & GitHub:
      - Overview: git/INDEX.md
      - Team Guidelines: git/GUIDELINES.md
      - Concepts: git/CONCEPTS.md
      - Workflow: git/WORKFLOW.md
      - Configuration: git/CONFIG.md
      - Advanced: git/ADVANCED.md
      - Recipes: git/RECIPES.md
  - Tutorials:
    - Git (Slidev): tutorials/GIT_TUTORIAL.md
    - Git — Embedded Slides: tutorials/GIT_TUTORIAL_EMBED.md
    - Git — Printable Summary: tutorials/GIT_TUTORIAL_SUMMARY.md
    - Conda Environments: tutorials/CONDA_TUTORIAL.md
    - Snakemake Basics: tutorials/SNAKEMAKE_TUTORIAL.md
    - GitHub Actions Basics: tutorials/GHA_TUTORIAL.md
  - Releases: RELEASES.md
  - Decision Guide: DECISION_GUIDE.md
  - Diagrams: DIAGRAMS.md
  - Handbook:
      - Policy & Principles: manual/01_POLICY_AND_PRINCIPLES.md
      - Project Setup: manual/02_PROJECT_SETUP.md
      - Metadata & Documentation: manual/03_METADATA_AND_DOCUMENTATION.md
      - Data Lifecycle: manual/04_DATA_LIFECYCLE.md
      - File & Version Control: manual/05_FILE_AND_VERSION_CONTROL.md
      - Data Quality: manual/06_DATA_QUALITY.md
      - Sensitive Data: manual/07_SENSITIVE_DATA.md
      - Tools & Platforms: manual/08_TOOLS_AND_PLATFORMS.md
      - Publishing & Reuse: manual/09_PUBLISHING_AND_REUSE.md
      - Checklists & Templates: manual/10_CHECKLISTS_AND_TEMPLATES.md
      - Software Practices: manual/11_SOFTWARE_PRACTICES.md
  - Implementation Guide: IMPLEMENTATION_GUIDE.md
  - Examples:
      - Minimal Project: examples/minimal-project/README.md
  - Tools (How-to):
      - Dataset Docs Generator: tools/generator.md
