site_name: GCE Sustainable Code & Data Handbook
site_url: https://globalchangeecology.github.io/gce-sustainable-code-and-data-handbook/
repo_url: https://github.com/GlobalChangeEcology/gce-sustainable-code-and-data-handbook
repo_name: GlobalChangeEcology/gce-sustainable-code-and-data-handbook
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  logo: images/logo_only.jpg
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
extra_css:
  - css/chips.css

nav:
  - 1. Foundations & Motivation: 01_foundations.md
  - 2. Data Management: 02_data_management.md
  - 3. Code Management: 03_code_management.md
  - 4. Reproducible Workflows: 04_reproducible_workflows.md
  - 5. Collaboration & Open Science: 05_collaboration_open_science.md
  - 6. Practical Tools & Hands-on Skills: 06_practical_tools.md
  - 7. Case Studies & Applications: 07_case_studies.md
  - References: references.md
  - Practical Guidance: practical_guidance.md
  - Git & GitHub Tutorials:
      - Why Version Control?: git_github_tutorials/01_why_version_control.md
      - What is Git?: git_github_tutorials/02_what_is_git.md
      - What is GitHub?: git_github_tutorials/03_what_is_github.md
      - Git Basics: git_github_tutorials/04_git_basics.md
      - Push to GitHub: git_github_tutorials/05_push_to_github.md
      - GitHub Etiquette & Best Practices: git_github_tutorials/06_github_etiquette.md
